version: '3'
services:
  DST_DediServer:
    container_name: dst_server
    image: ghcr.io/cn-dst-developer/dedicated_server_docker:latest
    ports:
      # [服务器防火墙暴露端口]:[server.ini中设置的server_port]
      - 10998:10998/udp
      - 10999:10999/udp
    volumes:
      # 左侧修改为你的存档目录
      - ~/dst/saves:/root/.klei/DoNotStarveTogether
      - ~/dst/mods:/root/Steam/steamapps/common/Don't Starve Together Dedicated Server/mods
    environment:
      # 修改为你的存档名
      - CLUSTER_NAME=MyDediServer
