version: '3'
services:
  DST_DediServer:
    container_name: dst_server
    image: ghcr.io/cn-dst-developer/dediserver_docker:latest
    ports:
      # [服务器防火墙暴露端口]:[server.ini中设置的server_port]
      - 10998:10998/udp
      - 10999:10999/udp
    volumes:
      # 左侧修改为你的存档目录，是Cluster_1等的上层路径
      - ~/dst/saves:/usr/steamapps/dst/saves
      # 左侧修改为主机上储存mod目录，用以重建容器时mod不需要重新下载，此行非必需可删除
      - ~/dst/mods:/usr/steamapps/dst/dedicated_server/mods
      # 左侧修改为主机上储存v2版本mod目录，用以重建容器或切换存档时v2版本mod不需要重新下载，此行非必需可删除
      - ~/dst/ugc_mods:/usr/steamapps/workshop/content/322330
    environment:
      # 修改为你的存档名，默认为MyDediServer，此行非必需可删除
      - CLUSTER_NAME=MyDediServer
    logging:
      options:
        max-size: 10m
        max-file: "3"

